language: php

php:
  - 7.1

before_script:
  - mysql -e 'create database IF NOT EXISTS symfony;'
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer selfupdate
  - composer install

script:
  - vendor/phpunit/phpunit/phpunit -c app

notifications:
  email:
    - david@flux.cat

branches:
  only:
    - master
    - devel
